baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Programming Note'
theme = 'hugo-book-main'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow markdown compiler to prersent raw HTML

[markup.goldmark.parser.attribute]
  block = true # Allow to add attribute to block

[params]
  BookTheme = 'auto'
  BookFavicon = '/img/avatar.png'
  BookToC = true
  BookLogo = '/img/avatar.png'
  