baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My programming note'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookCodeCopy = false