baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My programming note'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow markdown compiler to prersent raw HTML

[markup.goldmark.parser.attribute]
  block = true # Allow to add attribute to block