baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Programming Note'
theme = 'hugo-book-main'

minify = true
enableGitInfo = true
buildDrafts = false
buildFuture = false

[params]
  BookShowDraftBadge = false