name: Create Pull Request

# Run on push to any branch except main
on:
  push:
    branches-ignore:
      - "main"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    # Give permisson to create or edit pull request
    # Give permisson to read and write repsitory content for running gh CLI
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Check if pull request already exist
      - name: Check if PR already exists
        id: check_pr
        run: |
          PR_COUNT=$(gh pr list \
            --base main \
            --head ${{ github.ref_name }} \
            --state open \
            --json number \
            --jq 'length')
            
          if [ "$PR_COUNT" -eq 0 ]; then
            echo "No OPEN PR found. Proceeding to create one."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "An open PR already exists. Skipping creation."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}

      # If no pull request exist, create one
      - name: Create Pull Request
        if: steps.check_pr.outputs.exists == 'false'
        run: |
          gh pr create \
            --base main \
            --title "WIP: ${{ github.ref_name }}" \
            --body "Auto create pull request from branch **${{ github.ref_name }}**." \
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
