name: Check Broken Links

on:
  pull_request:
    branches: ["main"]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      # Get code
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Action
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          # Check files in /content
          # Return fail if any error occur
          fail: true
          # Add flag --verbose to view run detail
          # Add flag --exclude 403 (forbidden) since some websites may check for bot access
          args: --verbose --exclude 403 ./content
        env:
          # GitHub Token for action to return result
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
